# Generated by Django 5.2.4 on 2025-07-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='e_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='m_date',
            field=models.DateField(null=True),
        ),
    ]
