# Generated by Django 5.2.4 on 2025-07-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_e_date_alter_product_m_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='e_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='m_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
